export const CATEGORY = 'CATEGORY';
export const CATEGORY_TEMP = 'CATEGORY_TEMP';
export const CATEGORY_LOADING = 'CATEGORY_LOADING';
export const CATEGORY_MESSAGE = 'CATEGORY_MESSAGE';
export const CATEGORY_ERROR = 'CATEGORY_ERROR';
//
